/*
	Recipes constants
*/
export const FETCH_RECIPE = 'FETCH_RECIPE'
export const INCREMENT_RECIPE_PORTION = 'INCREMENT_RECIPE_PORTION'
export const DECREMENT_RECIPE_PORTION = 'DECREMENT_RECIPE_PORTION'

export const FETCH_RECIPE_LOADING = 'FETCH_RECIPE_LOADING'
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS'
export const FETCH_RECIPE_ERROR = 'FETCH_RECIPE_ERROR'

export const RESET_RECIPE = 'RESET_RECIPE'

/*
	Promise middleware actions
*/
export const LOADING = 'LOADING'
export const SUCCESS = 'SUCCESS'
export const ERROR = 'ERROR'
/*
	Categories constants
*/
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CATEGORY_BY_ID = 'FETCH_CATEGORY_BY_ID'

export const FETCH_CATEGORIES_LOADING = 'FETCH_CATEGORIES_LOADING'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR'

/*
	Cards constants
*/
export const FETCH_CARDS = 'FETCH_CARDS'
export const FAV_CARD = 'FAV_CARD'

/*
	Navigation constants
*/
export const NAVIGATE = 'NAVIGATE'
export const NAV_PUSH = 'NAV_PUSH'
export const NAV_POP = 'NAV_POP'
export const NAV_JUMP_TO_KEY = 'NAV_JUMP_TO_KEY'
export const NAV_JUMP_TO_INDEX = 'NAV_JUMP_TO_INDEX'
export const NAV_RESET = 'NAV_RESET'

/*
	General constants
*/
export const SET_CURRRENT_RECIPE = 'SET_CURRRENT_RECIPE'
export const IS_FETCHED_CATEGORIES = 'IS_FETCHED_CATEGORIES'

/*
	Recipe swiper constants
*/

export const SLIDER_NEXT_SLIDE = 'SLIDER_NEXT_SLIDE'
export const SLIDER_PREVIOUS_SLIDE = 'SLIDER_PREVIOUS_SLIDE'
export const SLIDER_SET_CURRENT_SLIDE = 'SLIDER_SET_CURRENT_SLIDER'
export const SLIDER_SET_INITIAL_SLIDE = 'SLIDER_SET_INITIAL_SLIDE'
export const SLIDER_HANDLE_SWIPE = 'SLIDER_HANDLE_SWIPE'
export const SLIDER_PUSH_CARDS_HEIGHTS = 'SLIDER_PUSH_CARDS_HEIGHTS'
export const SLIDER_RESET = 'SLIDER_RESET'

/*
	Search Actions
*/

export const SEARCH_GO = 'SEARCH_GO'
export const SEARCH_GO_LOADING = 'SEARCH_GO_LOADING'
export const SEARCH_GO_SUCCESS = 'SEARCH_GO_SUCCESS'
export const SEARCH_GO_ERROR = 'SEARCH_GO_ERROR'

/*
	History Actions
*/
export const ADD_TO_HISTORY = 'ADD_TO_HISTORY'
export const CLEAR_HISTORY = 'CLEAR_HISTORY'
export const REMOVE_FROM_HISTORY = 'REMOVE_FROM_HISTORY'
export const FETCH_HISTORY = 'FETCH_HISTORY'
export const FETCH_HISTORY_LOADING = 'FETCH_HISTORY_LOADING'
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS'
export const FETCH_HISTORY_ERROR = 'FETCH_HISTORY_ERROR'
