/*
	Recipes constants
*/
export const FETCH_RECIPE = 'FETCH_RECIPE'
export const INCREMENT_RECIPE_PORTION = 'INCREMENT_RECIPE_PORTION'
export const DECREMENT_RECIPE_PORTION = 'DECREMENT_RECIPE_PORTION'
export const SET_PRODUCT_AS_MAIN = 'SET_PRODUCT_AS_MAIN'
export const SET_PRODUCT_AS_EXTRA = 'SET_PRODUCT_AS_EXTRA'

export const FETCH_RECIPE_LOADING = 'FETCH_RECIPE_LOADING'
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS'
export const FETCH_RECIPE_ERROR = 'FETCH_RECIPE_ERROR'

export const RESET_RECIPE = 'RESET_RECIPE'

/*
	Promise middleware actions
*/
export const LOADING = 'LOADING'
export const SUCCESS = 'SUCCESS'
export const ERROR = 'ERROR'
/*
	Categories constants
*/

export const FETCH_JUMBOTRON = 'FETCH_JUMBOTRON'
export const FETCH_JUMBOTRON_LOADING = 'FETCH_JUMBOTRON_LOADING'
export const FETCH_JUMBOTRON_SUCCESS = 'FETCH_JUMBOTRON_SUCCESS'
export const FETCH_JUMBOTRON_ERROR = 'FETCH_JUMBOTRON_ERROR'

export const FETCH_RECOMMEND = 'FETCH_RECOMMEND'
export const FETCH_RECOMMEND_LOADING = 'FETCH_RECOMMEND_LOADING'
export const FETCH_RECOMMEND_SUCCESS = 'FETCH_RECOMMEND_SUCCESS'
export const FETCH_RECOMMEND_ERROR = 'FETCH_RECOMMEND_ERROR'

export const FETCH_CATEGORY = 'FETCH_CATEGORY'
export const FETCH_CATEGORY_LOADING = 'FETCH_CATEGORY_LOADING'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR'

/*
	Cards constants
*/
export const FETCH_CARDS = 'FETCH_CARDS'
export const FAV_CARD = 'FAV_CARD'

/*
	Navigation constants
*/
export const NAVIGATE = 'NAVIGATE'
export const NAV_PUSH = 'NAV_PUSH'
export const NAV_POP = 'NAV_POP'
export const NAV_JUMP_TO_KEY = 'NAV_JUMP_TO_KEY'
export const NAV_JUMP_TO_INDEX = 'NAV_JUMP_TO_INDEX'
export const NAV_RESET = 'NAV_RESET'

/*
	General constants
*/
export const SET_CURRRENT_RECIPE = 'SET_CURRRENT_RECIPE'
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
export const SAVE_IN_LAST_VIEWED = 'SAVE_IN_LAST_VIEWED'

/*
	Recipe swiper constants
*/

export const SLIDER_NEXT_SLIDE = 'SLIDER_NEXT_SLIDE'
export const SLIDER_PREVIOUS_SLIDE = 'SLIDER_PREVIOUS_SLIDE'
export const SLIDER_SET_CURRENT_SLIDE = 'SLIDER_SET_CURRENT_SLIDER'
export const SLIDER_SET_INITIAL_SLIDE = 'SLIDER_SET_INITIAL_SLIDE'
export const SLIDER_HANDLE_SWIPE = 'SLIDER_HANDLE_SWIPE'
export const SLIDER_PUSH_CARDS_HEIGHTS = 'SLIDER_PUSH_CARDS_HEIGHTS'
export const SLIDER_RESET = 'SLIDER_RESET'
export const SLIDER_GO_TO = 'SLIDER_GO_TO'
export const SLIDER_GO_TO_START = 'SLIDER_GO_TO_START'

/*
	Search Actions
*/

export const SEARCH_GO = 'SEARCH_GO'
export const SEARCH_GO_LOADING = 'SEARCH_GO_LOADING'
export const SEARCH_GO_SUCCESS = 'SEARCH_GO_SUCCESS'
export const SEARCH_GO_ERROR = 'SEARCH_GO_ERROR'

/*
	History Actions
*/
export const ADD_TO_SAVED_RECIPES = 'ADD_TO_SAVED_RECIPES'
export const CLEAR_HISTORY = 'CLEAR_HISTORY'
export const REMOVE_FROM_SAVED_RECIPES = 'REMOVE_FROM_SAVED_RECIPES'
export const FETCH_SAVED_RECIPES = 'FETCH_SAVED_RECIPES'
export const FETCH_SAVED_RECIPES_LOADING = 'FETCH_SAVED_RECIPES_LOADING'
export const FETCH_SAVED_RECIPES_SUCCESS = 'FETCH_SAVED_RECIPES_SUCCESS'
export const FETCH_SAVED_RECIPES_ERROR = 'FETCH_SAVED_RECIPES_ERROR'
export const FETCH_LAST_VIEWED = 'FETCH_LAST_VIEWED'
export const FETCH_LAST_VIEWED_LOADING = 'FETCH_LAST_VIEWED_LOADING'
export const FETCH_LAST_VIEWED_SUCCESS = 'FETCH_LAST_VIEWED_SUCCESS'
export const FETCH_LAST_VIEWED_ERROR = 'FETCH_LAST_VIEWED_ERROR'

/*
	Timers actions
*/
export const SET_TIMER = 'SET_TIMER'
export const REMOVE_TIMER = 'REMOVE_TIMER'
export const SORT_TIMERS = 'SORT_TIMERS'
export const RESET_TIMERS = 'RESET_TIMERS'
export const PAUSE_TIMER = 'PAUSE_TIMER'
