export const SAVED_RECIPES_STORAGE_KEY = '@AsyncStorageHistory:key'
// export const HISTORY_STORAGE_VERSION = '@AsyncStorageHistoryVersion:key'
export const RECIPES_STORAGE_KEY = '@AsyncStorageRecipes:key'
// export const RECIPES_STORAGE_VERSION = '@AsyncStorageRecipesVersion:key'
// export const CATEGORY_STORAGE_KEY = '@AsyncStorageCategory:key'
// export const CATEGORY_STORAGE_VERSION = '@AsyncStorageCategoryVersion:key'
export const LAST_VIEWED_KEY = '@AsyncStorageLastViewed:key'
